name: ElytraBooster
version: 0.01
description: Gives Elytras a fiery Boost!
main: de.oninoni.ElytraBooster.ElytraBooster
depend: [OnionPower]
commands:
  elytra:
    description: Giving you a boosted Elytra
    permission: elytra.admin
    usage: Do /<command> to get a boosted elytra