name: OnionPower
main: de.oninoni.OnionPower.OnionPower
description: THIS IS AWESOME POWER THING!
version: 0.42.006
commands:
  poweritems:
    description: Opens Inventory with all PowerItems inside
    usage: Nope
  upgrades:
    description: Opens Inventory with all Upgrades inside
    usage: Nope