name: OnionPower
main: de.oninoni.OnionPower.OnionPower
description: THIS IS AWESOME POWER THING!
version: 0.42.006
commands:
  poweritems:
    description: Opens Items with all PowerItems inside
    usage: Nope